### ISSUE TITLE
add on-the-fly CMake for speexdsp VisualStudio build

### ISSUE THREAD

**Issue by qno** [qno/Rack#1]
After checkout sources step generate a CMakeLists.txt with following content:

```cmake
cmake_minimum_required (VERSION 3.12)
project (SpeexDSP VERSION 1.2)

set (LIBSPEEXDSP "libspeexdsp")

if (NOT MSVC)
  message (FATAL_ERROR "Abort proccessing - this CMake project has only support for MS Visual Studio!")
endif ()

set (SOURCES libspeexdsp/buffer.c
             libspeexdsp/fftwrap.c
             libspeexdsp/filterbank.c
             libspeexdsp/jitter.c
             libspeexdsp/kiss_fft.c
             libspeexdsp/kiss_fftr.c
             libspeexdsp/mdf.c
             libspeexdsp/preprocess.c
             libspeexdsp/resample.c
             libspeexdsp/scal.c
             libspeexdsp/smallft.c)

add_library (${LIBSPEEXDSP} ${SOURCES})

target_include_directories (${LIBSPEEXDSP} PRIVATE include libspeexdsp win32)
target_compile_definitions (${LIBSPEEXDSP} PRIVATE D_LIB HAVE_CONFIG_H)
```

**Comment by qno** [comment]
https://gist.github.com/mbinna/c61dbb39bca0e4fb7d1f73b0d66a4fd1

**Comment by kdudnyk** [comment]
looks like Rack supports linux - we should also support it! please create an issue - maybe such cmake support will be added auto-magically by someone (assign it to me ;)?

**Comment by kdudnyk** [comment]
By the way we can use https://cmake.org/cmake/help/v3.11/module/FetchContent.html - this will download dependencies sources at configuration step - so there will be no need to explicitly generate cmake

**Comment by qno** [comment]
@kdudnyk - now take a look here ;-)

https://github.com/qno/conan-speexdsp and https://github.com/qno/conan-speexdsp/pull/1
